title: El vivero
author: El vivero
social:
  name: El vivero
  links: 
    - https://www.instagram.com/elviverodesign/
    - https://www.linkedin.com/company/el-vivero/
description: "El vivero design studio began as the partnership between Leandro Lattes and Florencia Grassi in 2004. Based in Madrid, we collaborate with major cultural, art, science and tourism organizations, as well as many other clients in Spain and abroad."
url: "https://elvivero.es"
baseurl: ""
lang: "en"

google_analytics: "UA-132768107-1"

sass:
    sass_dir: _sass
    style: compressed

plugins: [jekyll-paginate, jekyll-sitemap, jekyll-seo-tag, jekyll-readme-index]

readme_index:
  enabled:          true
  remove_originals: true

permalink: /:title/
exclude: 
  - README.md
  - escaparate.command
  - notes.md
  - CNAME
  - run.sh
  - todo.md
  - Gemfile
  - Gemfile.lock
  - _posts/2018-01-01-template.html
  - translate-links.txt
  - default.nix
  - Makefile
  - gemset.nix
